name: HeyBox 每日签到

on:
  schedule:
    - cron: '5 16 * * *'  # 北京时间凌晨 00:05
  workflow_dispatch:

jobs:
  heybox-daily:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Cache HeyBox Data
        uses: actions/cache@v4
        with:
          path: cache
          key: heybox-data-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ github.run_id }}
          restore-keys: |
            heybox-data-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            heybox-data-cache-${{ runner.os }}-

      - name: 每日任务全量自动执行与微信推送
        env:
          heybox_ck: ${{ secrets.HEYBOX_CK }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          BARK_URL: ${{ secrets.BARK_URL }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: node heybox_all.js
