name: HeyBox 每日签到

on:
  schedule:
    - cron: '5 16 * * *'  # 北京时间 00:05
    - cron: '0 0 * * *'   # 北京时间 08:00
  workflow_dispatch:

jobs:
  heybox-daily:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Cache HeyBox Data
        uses: actions/cache@v4
        with:
          path: cache
          key: heybox-data-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ github.run_id }}
          restore-keys: |
            heybox-data-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            heybox-data-cache-${{ runner.os }}-

      - name: 每日签到
        env:
          heybox_ck: ${{ secrets.HEYBOX_CK }}
        run: node heybox_sign.js

      - name: 普通领券
        env:
          heybox_ck: ${{ secrets.HEYBOX_CK }}
        run: node heybox_claim.js

      - name: 抽奖盒券
        env:
          heybox_ck: ${{ secrets.HEYBOX_CK }}
        run: node heybox_roll.js
